defmodule Bank.Decisions.ReportMarkdown do
  @moduledoc """
  Markdown renderer for `Bank.Decisions.Report` (#249).

  Pure function: same `%Bank.Decisions.Report{}` in → byte-stable
  Markdown out, every render. The report struct is already
  deterministic (#248) and secret-redacted (#248 P2 / PR #360);
  this module only projects those safe fields into Markdown.

  ## Section ordering

  Top-to-bottom, fixed:

    1. Header (intent id, workspace id, report version)
    2. Chain context (chain, mainnet/testnet, live/stub)
    3. Intent
    4. Actor / source
    5. Decision envelope (or labelled missing)
    6. Approval / rejection (or labelled missing)
    7. Trust assessment (or labelled missing)
    8. Simulation (or labelled missing)
    9. Screening evidence (or labelled missing)
    10. Policy snapshot (table, or labelled missing)
    11. Execution plan (or labelled missing)
    12. Stablecoin route evidence (or "(none)")
    13. Audit trail (table, or "(none)")
    14. Residual limitations (or "(none)")
    15. Footer disclaimer — replay-derived; no safety/production
        claim is implied.

  ## Tone — no safety overclaim

  Verbs deliberately stay neutral: "recorded", "captured",
  "reported", "observed". The renderer never claims a decision
  is "safe", "approved as production-ready", or "successfully
  executed". The footer makes the replay-derived nature explicit.

  ## Secret hygiene

  The `%Report{}` struct already excludes `signing_requirements`,
  audit `before_ref`/`after_ref` payloads, raw policy `params`
  values, and operator-supplied `reasons.items[].message` /
  `details` (#248 + #248 P2 / PR #360). The renderer additionally:

    * Renders redacted reason items as a one-line placeholder
      that names the safe `code` + `actor_id` only, never any
      `message`/`details` shape that may have been added later.
    * Allowlists `execution_plan.final_reason` to a small set of
      runtime-generated codes. `execution.reverted` /
      `execution.aborted` adapter callbacks write
      `params["reason"]` straight into this column, so any free-
      text body that does not match an allowlisted code is
      rendered as `(redacted free-text reason)` (#249 P2).
    * Allowlists `stablecoin_route_evidence` to a fixed set of
      scalar evidence fields (`decision`, `execution_state`,
      `reason_code`, `policy_decision`, `provider`, `route_kind`,
      `input_amount`, `output_amount`, `evaluated_at`, etc.) plus
      a small fee-summary subset. Nested raw shapes
      (`quote_request`, `legs`, `selector_metadata`,
      `policy_reasons`, `reason`) are NOT rendered (#249 P2).
    * Allowlists every renderable raw-address surface
      (`intent.target.address` for the raw-address target kind +
      `screening_evidence.screened_address`) to the EVM
      `0x[a-f0-9]{40}` shape. `Bank.Intents` accepts any non-empty
      `target_raw_address` string and the screening flow echoes
      the same value into `screened_address`, so an agent or
      operator could otherwise paste an Authorization header, a
      `sk_(test|live)_…` token, a tokenized URL, or a PEM marker
      into the field and have it render verbatim into the
      exported decision report. Anything that does not match the
      EVM-address shape collapses to
      `(redacted non-address raw target)` (#250 P2).
    * Truncates long ids in tables for readability without
      exposing additional fields.
    * Wraps every value in backticks so a stray newline or
      pipe character cannot break the table layout (defensive).

  ## Determinism

    * Iterates struct fields in fixed order (no `Map.to_list/1`).
    * Reads list fields in the order the Report builder produced
      them (already deterministic per #248).
    * No `DateTime.utc_now/0`, no `:rand`, no IO.
  """

  alias Bank.Decisions.Report

  @id_short_chars 8

  # `execution_plan.final_reason` is set by several runtime paths.
  # Some are programmer-generated atoms; some are free text from
  # adapter callback `params["reason"]` (`execution.reverted` /
  # `execution.aborted` in `lib/bank/decisions.ex`). The free-text
  # path can carry pasted Authorization headers, RPC URLs with
  # embedded credentials, PEM markers, `sk_` / `pk_` tokens, or
  # 0x-prefixed key handles. Default-deny: only render values that
  # match an explicit allowlisted shape; everything else collapses
  # to `(redacted free-text reason)` (#249 P2).
  @safe_final_reason_atoms ~w(
    runtime_paused
    chain_paused
    delegation_not_active
    operator_requested
    sandbox_seed
  )

  # `target_not_resolvable:<cause>` is generated by
  # `lib/bank/runtime/workers/run_execution.ex` from a closed enum
  # of causes. Allowlist the suffixes so a future renamed cause does
  # not silently leak.
  @safe_target_unresolvable_causes ~w(
    intent_missing
    label_retired
    label_missing
    no_label
    ambiguous_label
    missing_target
  )

  # `stablecoin.route_evaluated` audit `after_ref` is built by
  # `Bank.Stablecoins.IntentRouting.build_evidence/1` and replayed
  # into `bundle.stablecoin_route_evidence` as a list of route maps.
  # Only render the scalar evidence fields a reviewer needs to
  # follow the routing decision; keep nested shapes off the render
  # surface (#249 P2).
  @stablecoin_route_safe_keys ~w(
    decision
    execution_state
    reason_code
    policy_decision
    provider
    route_kind
    input_amount
    output_amount
    score
    eta_seconds
    quoted_at
    evaluated_at
    expires_at
  )

  @stablecoin_route_safe_fee_keys ~w(
    total_fee
    gas_fee
    protocol_fee
    bridge_fee
    cryptobank_fee
    output_impact_pct
  )

  @spec render(Report.t()) :: String.t()
  def render(%Report{} = r) do
    [
      header(r),
      "\n",
      chain_context(r.flags),
      "\n",
      intent_section(r.intent),
      "\n",
      actor_source_section(r.actor_source),
      "\n",
      decision_envelope_section(r.decision_envelope),
      "\n",
      approval_section(r.approval),
      "\n",
      trust_section(r.trust_assessment),
      "\n",
      simulation_section(r.simulation),
      "\n",
      screening_section(r.screening_evidence),
      "\n",
      policy_section(r.policy_snapshot),
      "\n",
      execution_plan_section(r.execution_plan),
      "\n",
      stablecoin_routes_section(r.stablecoin_routes),
      "\n",
      audit_trail_section(r.audit_trail),
      "\n",
      residual_limitations_section(r.residual_limitations),
      "\n",
      footer()
    ]
    |> IO.iodata_to_binary()
  end

  # --- header ---------------------------------------------------------------

  defp header(%Report{version: version, generated_from: gf}) do
    intent_id = Map.get(gf, :intent_id) || "(unknown)"
    workspace_id = Map.get(gf, :workspace_id) || "(unscoped)"

    [
      "# Decision report\n",
      "\n",
      "- Report version: `",
      version,
      "`\n",
      "- Intent: `",
      intent_id,
      "`\n",
      "- Workspace: `",
      workspace_id,
      "`\n"
    ]
  end

  # --- chain context --------------------------------------------------------

  defp chain_context(flags) do
    chain = Map.get(flags, :chain) || "(unknown)"
    network = network_label(flags)
    execution = execution_label(flags)

    [
      "## Chain context\n",
      "\n",
      "- Chain: `",
      chain,
      "`\n",
      "- Network: ",
      network,
      "\n",
      "- Execution path: ",
      execution,
      "\n"
    ]
  end

  defp network_label(%{mainnet?: true}),
    do: "**mainnet** (chain-broadcast plans persist real funds)"

  defp network_label(%{testnet?: true}), do: "testnet"
  defp network_label(_), do: "(unknown)"

  defp execution_label(%{live?: true}),
    do: "live (at least one execution plan reached broadcasting/pending/confirmed)"

  defp execution_label(%{stub?: true}),
    do: "stub (no execution plan reached chain-broadcast state)"

  defp execution_label(_), do: "(unknown)"

  # --- intent ---------------------------------------------------------------

  defp intent_section(intent) do
    [
      "## Intent\n",
      "\n",
      "| Field | Value |\n",
      "| --- | --- |\n",
      kv_row("ID", short(intent[:id])),
      kv_row("Kind", intent[:kind]),
      kv_row("Asset", intent[:asset]),
      kv_row("Chain", intent[:chain]),
      kv_row("Amount", intent[:amount]),
      kv_row("State", intent[:state]),
      kv_row("Idempotency key", intent[:idempotency_key]),
      kv_row("Submitted at", intent[:submitted_at]),
      kv_row("Target", target_label(intent[:target]))
    ]
  end

  defp target_label(%{kind: "counterparty"} = t),
    do:
      "counterparty: " <> short(t[:counterparty_id]) <> address_label_suffix(t[:address_label_id])

  defp target_label(%{kind: "raw_address"} = t),
    do: "raw_address: " <> safe_raw_address(t[:address])

  defp target_label(%{kind: "unspecified"}), do: "(unspecified)"
  defp target_label(_), do: "(unknown)"

  defp address_label_suffix(nil), do: ""
  defp address_label_suffix(id), do: " (address_label: " <> short(id) <> ")"

  # --- actor / source ------------------------------------------------------

  defp actor_source_section(actor) do
    [
      "## Actor / source\n",
      "\n",
      "- Agent: `",
      actor[:agent_id] || "(unknown)",
      "`\n",
      "- Source: `",
      actor[:source] || "(unknown)",
      "`\n",
      "- Workspace: `",
      actor[:workspace_id] || "(unscoped)",
      "`\n"
    ]
  end

  # --- decision envelope ---------------------------------------------------

  defp decision_envelope_section(%{available: false, reason: reason}) do
    section_missing("Decision envelope", reason)
  end

  defp decision_envelope_section(d) do
    reasons_block =
      case d[:reasons] do
        %{item_count: 0} ->
          "_(no recorded reasons)_\n"

        %{items: items} when is_list(items) ->
          ["Reasons:\n" | Enum.map(items, &reason_bullet/1)]

        _ ->
          "_(no recorded reasons)_\n"
      end

    [
      "## Decision envelope\n",
      "\n",
      "- ID: `",
      short(d[:id]),
      "`\n",
      "- Outcome: `",
      d[:outcome] || "(unknown)",
      "`\n",
      "- Risk tier: `",
      d[:risk_tier] || "(unknown)",
      "`\n",
      "- Decided at: `",
      d[:decided_at] || "(unknown)",
      "`\n",
      "- Decided by: `",
      d[:decided_by] || "(unknown)",
      "`\n",
      "- State: `",
      d[:state] || "(unknown)",
      "`\n",
      "\n",
      reasons_block
    ]
  end

  # Bare-string reason items are programmer-written labels (e.g.
  # `"policy.amount_limit ok"`). Map items are the operator
  # approval/rejection redacted shape from PR #360. The renderer
  # MUST NOT look at any `message` or `details` field here — the
  # Report builder strips them, but defend in depth.
  defp reason_bullet(text) when is_binary(text), do: ["  - `", text, "`\n"]

  defp reason_bullet(%{} = item) do
    code = Map.get(item, "code") || Map.get(item, :code) || "(unknown)"
    actor_id = Map.get(item, "actor_id") || Map.get(item, :actor_id)
    redacted? = Map.get(item, "redacted") || Map.get(item, :redacted)

    actor_suffix =
      case actor_id do
        nil -> ""
        id -> ", actor: `" <> short(id) <> "`"
      end

    suffix =
      if redacted?,
        do: " — operator-supplied body redacted (#248 P2 secret-hygiene)",
        else: ""

    ["  - code: `", to_string(code), "`", actor_suffix, suffix, "\n"]
  end

  defp reason_bullet(_), do: "  - _(unrecognised reason item shape)_\n"

  # --- approval ------------------------------------------------------------

  defp approval_section(%{available: false, reason: reason}) do
    section_missing("Approval / rejection", reason)
  end

  defp approval_section(a) do
    [
      "## Approval / rejection\n",
      "\n",
      "- Kind: `",
      Map.get(a, :kind) || "(unknown)",
      "`\n",
      "- Decided by: `",
      Map.get(a, :decided_by) || "(n/a)",
      "`\n",
      "- Decided at: `",
      Map.get(a, :decided_at) || "(n/a)",
      "`\n"
    ]
  end

  # --- trust ----------------------------------------------------------------

  defp trust_section(%{available: false, reason: reason}) do
    section_missing("Trust assessment", reason)
  end

  defp trust_section(t) do
    [
      "## Trust assessment\n",
      "\n",
      "- Derived trust: `",
      t[:derived_trust] || "(unknown)",
      "`\n",
      "- Confidence: `",
      t[:confidence] || "(unknown)",
      "`\n",
      "- Generated at: `",
      t[:generated_at] || "(unknown)",
      "`\n",
      "- Generated by: `",
      t[:generated_by] || "(unknown)",
      "`\n",
      "- Contradictions: `",
      to_string(t[:contradictions_count] || 0),
      "`\n",
      "- Supporting assertions: `",
      to_string(length(t[:supporting_assertion_ids] || [])),
      "`\n",
      "- Supporting evidence: `",
      to_string(length(t[:supporting_evidence_ids] || [])),
      "`\n"
    ]
  end

  # --- simulation -----------------------------------------------------------

  defp simulation_section(%{available: false, reason: reason}) do
    section_missing("Simulation", reason)
  end

  defp simulation_section(s) do
    [
      "## Simulation\n",
      "\n",
      "- Provider: `",
      s[:provider] || "(unknown)",
      "`\n",
      "- Provider trace ref: `",
      s[:provider_trace_ref] || "(none)",
      "`\n",
      "- Status: `",
      s[:status] || "(unknown)",
      "`\n",
      "- Estimated gas: `",
      to_string(s[:estimated_gas] || "(n/a)"),
      "`\n",
      "- Expected output: `",
      to_string(s[:expected_output] || "(n/a)"),
      "`\n",
      "- Slippage exposure: `",
      to_string(s[:slippage_exposure] || "(n/a)"),
      "`\n",
      "- Predicted balance changes: `",
      to_string(s[:predicted_balance_change_count] || 0),
      "`\n",
      "- Failure conditions: `",
      to_string(s[:failure_condition_count] || 0),
      "`\n"
    ]
  end

  # --- screening ------------------------------------------------------------

  defp screening_section(%{available: false, reason: reason}) do
    section_missing("Screening evidence", reason)
  end

  defp screening_section(s) do
    [
      "## Screening evidence\n",
      "\n",
      "- Outcome: `",
      s[:outcome] || "(unknown)",
      "`\n",
      "- Screened address: `",
      safe_raw_address(s[:screened_address]),
      "`\n",
      "- Screened chain: `",
      s[:screened_chain] || "(none)",
      "`\n",
      "- Winning tier: `",
      s[:winning_tier] || "(none)",
      "`\n",
      "- Winning source: `",
      s[:winning_source] || "(none)",
      "`\n",
      "- Total records: `",
      to_string(s[:total_records] || 0),
      "`\n"
    ]
  end

  # --- policy snapshot table ----------------------------------------------

  defp policy_section(%{available: false, reason: reason}) do
    section_missing("Policy snapshot", reason)
  end

  defp policy_section(%{rules: rules}) when is_list(rules) and rules != [] do
    rows = Enum.map(rules, &policy_row/1)

    [
      "## Policy snapshot\n",
      "\n",
      "Total rules captured: `",
      to_string(length(rules)),
      "`\n",
      "\n",
      "| Rule | Type | Priority | State | Version | Param keys |\n",
      "| --- | --- | --- | --- | --- | --- |\n"
      | rows
    ]
  end

  defp policy_section(_), do: section_missing("Policy snapshot", "no policy rules captured")

  defp policy_row(rule) do
    keys = (rule[:param_keys] || []) |> Enum.join(", ")

    [
      "| `",
      short(rule[:id]),
      "` | `",
      to_string(rule[:rule_type] || ""),
      "` | `",
      to_string(rule[:priority] || ""),
      "` | `",
      to_string(rule[:state] || ""),
      "` | `",
      to_string(rule[:version] || ""),
      "` | `",
      keys,
      "` |\n"
    ]
  end

  # --- execution plan -------------------------------------------------------

  defp execution_plan_section(%{available: false, reason: reason}) do
    section_missing("Execution plan", reason)
  end

  defp execution_plan_section(p) do
    tx_refs =
      case p[:tx_refs] do
        [] -> "(none)"
        list when is_list(list) -> Enum.join(list, ", ")
        _ -> "(none)"
      end

    [
      "## Execution plan\n",
      "\n",
      "- Plan ID: `",
      short(p[:id]),
      "`\n",
      "- Decision ID: `",
      short(p[:decision_id]),
      "`\n",
      "- Chain: `",
      p[:chain] || "(unknown)",
      "`\n",
      "- Asset: `",
      p[:asset] || "(unknown)",
      "`\n",
      "- Smart account: `",
      p[:smart_account_id] || "(unknown)",
      "`\n",
      "- Execution status: `",
      p[:execution_status] || "(unknown)",
      "`\n",
      "- Final outcome: `",
      p[:final_outcome] || "(none)",
      "`\n",
      "- Final reason: `",
      safe_final_reason(p[:final_reason]),
      "`\n",
      "- Adapter ref: `",
      p[:adapter_ref] || "(none)",
      "`\n",
      "- Nonce: `",
      to_string(p[:nonce] || "(none)"),
      "`\n",
      "- Active: `",
      to_string(Map.get(p, :active, false)),
      "`\n",
      "- Tx refs: `",
      tx_refs,
      "`\n"
    ]
  end

  # --- stablecoin routes ---------------------------------------------------

  defp stablecoin_routes_section([]) do
    [
      "## Stablecoin route evidence\n",
      "\n",
      "_(none recorded)_\n"
    ]
  end

  defp stablecoin_routes_section(routes) when is_list(routes) do
    rendered = Enum.map(routes, &stablecoin_route_bullet/1)

    [
      "## Stablecoin route evidence\n",
      "\n",
      "Captured route evaluations: `",
      to_string(length(routes)),
      "`\n",
      "\n"
      | rendered
    ]
  end

  # Render one route as a key-value bullet group. Walks the
  # allowlist in fixed order; unknown keys (`quote_request`,
  # `legs`, `selector_metadata`, `policy_reasons`, `reason`, future
  # additions) are dropped on the floor by construction. Real
  # `after_ref` payloads come back from the DB as string-keyed
  # maps, but the in-memory shape is atom-keyed — `route_value/2`
  # tries both.
  defp stablecoin_route_bullet(%{} = route) do
    scalar_lines =
      Enum.flat_map(@stablecoin_route_safe_keys, fn key ->
        case route_value(route, key) do
          nil -> []
          v -> [["    - ", key, ": `", scalar_to_iodata(v), "`\n"]]
        end
      end)

    fee_lines = stablecoin_route_fee_lines(route_value(route, "fee_summary"))

    case scalar_lines ++ fee_lines do
      [] -> ["- _(route entry has no allowlisted fields)_\n"]
      lines -> ["- Route:\n" | lines]
    end
  end

  defp stablecoin_route_bullet(_), do: "- _(route entry has unexpected shape)_\n"

  defp stablecoin_route_fee_lines(nil), do: []

  defp stablecoin_route_fee_lines(%{} = fees) do
    rendered =
      Enum.flat_map(@stablecoin_route_safe_fee_keys, fn key ->
        case route_value(fees, key) do
          nil -> []
          v -> [["      - ", key, ": `", scalar_to_iodata(v), "`\n"]]
        end
      end)

    case rendered do
      [] -> []
      _ -> [["    - fee_summary:\n" | rendered]]
    end
  end

  defp stablecoin_route_fee_lines(_), do: []

  defp route_value(map, key) when is_binary(key) do
    case Map.fetch(map, key) do
      {:ok, v} -> v
      :error -> Map.get(map, String.to_existing_atom(key), nil)
    end
  rescue
    ArgumentError -> Map.get(map, key, nil)
  end

  defp scalar_to_iodata(v) when is_binary(v), do: v
  defp scalar_to_iodata(v) when is_integer(v), do: Integer.to_string(v)
  defp scalar_to_iodata(v) when is_float(v), do: Float.to_string(v)
  defp scalar_to_iodata(v) when is_boolean(v), do: to_string(v)
  defp scalar_to_iodata(v) when is_atom(v) and not is_nil(v), do: Atom.to_string(v)
  defp scalar_to_iodata(_), do: "(opaque)"

  # --- audit trail table --------------------------------------------------

  defp audit_trail_section([]) do
    [
      "## Audit trail\n",
      "\n",
      "_(no audit events recorded)_\n"
    ]
  end

  defp audit_trail_section(events) when is_list(events) do
    rows = Enum.map(events, &audit_row/1)

    [
      "## Audit trail\n",
      "\n",
      "Total events: `",
      to_string(length(events)),
      "`\n",
      "\n",
      "| Timestamp | Event type | Actor | Subject |\n",
      "| --- | --- | --- | --- |\n"
      | rows
    ]
  end

  defp audit_row(event) do
    subject =
      [
        Map.get(event, :subject_type) || "(unknown)",
        "#",
        short(Map.get(event, :subject_id))
      ]

    [
      "| `",
      Map.get(event, :ts) || "(unknown)",
      "` | `",
      Map.get(event, :event_type) || "(unknown)",
      "` | `",
      to_string(Map.get(event, :actor) || "(unknown)"),
      "` | `",
      subject,
      "` |\n"
    ]
  end

  # --- residual limitations ------------------------------------------------

  defp residual_limitations_section([]) do
    [
      "## Residual limitations\n",
      "\n",
      "_(none — every optional section was populated)_\n"
    ]
  end

  defp residual_limitations_section(limits) when is_list(limits) do
    rendered = Enum.map(limits, fn l -> ["- ", l, "\n"] end)

    ["## Residual limitations\n", "\n" | rendered]
  end

  # --- footer / hygiene ---------------------------------------------------

  defp footer do
    """

    ---

    *This report is replay-derived from persisted decision, audit,
    and execution rows. No business logic was re-run during
    rendering. The report does not assert ongoing safety,
    post-decision compliance, or production readiness. Field values
    reflect what was recorded at the time of decision/execution.
    Operator-supplied free-text reasons are intentionally redacted
    here; consult the underlying `decision_envelopes` row for
    forensic review with appropriate database access.*
    """
  end

  # --- shared helpers -----------------------------------------------------

  defp section_missing(title, reason) do
    [
      "## ",
      title,
      "\n",
      "\n",
      "_(missing — ",
      reason || "no detail recorded",
      ")_\n"
    ]
  end

  defp kv_row(label, value) do
    ["| ", label, " | `", to_string(value || "(none)"), "` |\n"]
  end

  defp short(nil), do: "(none)"

  defp short(value) when is_binary(value) do
    case String.length(value) do
      n when n <= @id_short_chars -> value
      _ -> binary_part(value, 0, @id_short_chars) <> "…"
    end
  end

  defp short(other), do: to_string(other)

  # --- final_reason allowlist (#249 P2) -----------------------------------
  #
  # `execution_plan.final_reason` is set by:
  #
  #   * runtime atom strings (`runtime_paused`, `chain_paused`,
  #     `delegation_not_active`, `operator_requested`, `sandbox_seed`)
  #   * `target_not_resolvable:<atom_cause>` from
  #     `lib/bank/runtime/workers/run_execution.ex`
  #   * `adapter_rejected:<status>:<summary>` from the same module
  #     (the `<summary>` slice can be up to 80 chars of arbitrary
  #     adapter response body)
  #   * adapter callback `params["reason"]` for `execution.reverted`
  #     and `execution.aborted` in `lib/bank/decisions.ex` — fully
  #     untrusted operator/provider free text
  #
  # Default-deny: only render values that match an explicit
  # allowlisted shape. The `adapter_rejected` summary slice is
  # dropped (status code only is rendered) so a stray PEM marker /
  # Bearer token / token URL hidden inside an adapter error body
  # cannot leak into the Markdown report. Free text falls through to
  # `(redacted free-text reason)`.

  defp safe_final_reason(nil), do: "(none)"
  defp safe_final_reason(""), do: "(none)"

  defp safe_final_reason(reason) when is_binary(reason) do
    cond do
      reason in @safe_final_reason_atoms -> reason
      target_unresolvable_match?(reason) -> reason
      adapter_rejected_status_only(reason) != :no_match -> adapter_rejected_status_only(reason)
      true -> "(redacted free-text reason)"
    end
  end

  defp safe_final_reason(_), do: "(redacted free-text reason)"

  defp target_unresolvable_match?("target_not_resolvable:" <> cause),
    do: cause in @safe_target_unresolvable_causes

  defp target_unresolvable_match?(_), do: false

  # `adapter_rejected:<status>[:<summary>]`. Render only the prefix
  # + numeric status; drop the summary regardless of content because
  # `summarise_body/1` can put arbitrary adapter bytes there.
  defp adapter_rejected_status_only("adapter_rejected:" <> rest) do
    case String.split(rest, ":", parts: 2) do
      [status] ->
        if numeric_status?(status), do: "adapter_rejected:#{status}", else: :no_match

      [status, _summary] ->
        if numeric_status?(status), do: "adapter_rejected:#{status}", else: :no_match
    end
  end

  defp adapter_rejected_status_only(_), do: :no_match

  defp numeric_status?(s) when is_binary(s) do
    s != "" and String.match?(s, ~r/^\d+$/)
  end

  # --- raw target address allowlist (#250 P2) -----------------------------
  #
  # `Bank.Intents` accepts any non-empty `target_raw_address`
  # string. Agents/operators can therefore paste arbitrary content
  # (Authorization headers, `sk_(test|live)_…` tokens, RPC URLs
  # with embedded credentials, PEM markers) and have it render
  # verbatim into the exported decision report. Default-deny
  # against the EVM `0x[a-f0-9]{40}` shape (case-insensitive on
  # the hex body), which is the only address shape any v0.1 chain
  # in the codebase emits (`base`, `ethereum`, `base-sepolia`,
  # `sepolia`, `goerli`). Anything else collapses to
  # `(redacted non-address raw target)` so the export still tells
  # a reviewer that a raw_address target was set, just not what
  # operator-supplied bytes were in it.

  @evm_raw_address_regex ~r/^0x[a-fA-F0-9]{40}$/

  defp safe_raw_address(nil), do: "(none)"
  defp safe_raw_address(""), do: "(none)"

  defp safe_raw_address(value) when is_binary(value) do
    if String.match?(value, @evm_raw_address_regex),
      do: value,
      else: "(redacted non-address raw target)"
  end

  defp safe_raw_address(_), do: "(redacted non-address raw target)"
end
