defmodule Bank.Schema do
  @moduledoc """
  Shared Ecto schema defaults for every domain object.

  All domain schemas:

    * use UUID v4 primary keys (`:binary_id`) generated by the DB via
      `gen_random_uuid()`. Keys are stable for the life of the record.
    * use `:binary_id` for all foreign keys.
    * timestamp columns use `:utc_datetime_usec` so the microsecond
      precision on append-only records (audit, supersession chains) is
      preserved.

  Use it like any base schema module:

      defmodule Bank.Counterparties.Counterparty do
        use Bank.Schema
        schema "counterparties" do
          ...
          timestamps()
        end
      end
  """

  defmacro __using__(_opts) do
    quote do
      use Ecto.Schema

      import Ecto.Changeset

      @primary_key {:id, :binary_id, autogenerate: true}
      @foreign_key_type :binary_id
      @timestamps_opts [type: :utc_datetime_usec]
    end
  end
end
