defmodule BankWeb.OpenApi.Headers do
  @moduledoc """
  Reusable OpenAPI response header components for the external
  `/v1` API (issue #87, epic #85).

  Each function returns an `%OpenApiSpex.Header{}` value that
  `BankWeb.ApiSpec` registers under `components.headers`. Later
  issues reference headers by name:

      %OpenApiSpex.Reference{"$ref": "#/components/headers/RequestIdOut"}

  rather than redefining them in every operation.

  ## Components exposed

    * `RequestIdOut` — `X-Request-Id` response header. Phoenix
      echoes the value that came in on the request (or the fresh
      id it generated when the request had none). Consumers use
      this for log correlation.
  """

  alias OpenApiSpex.{Header, Schema}

  @doc """
  `X-Request-Id` response header. Always present; value is the
  one echoed from the request or generated by Phoenix.
  """
  @spec request_id_out() :: Header.t()
  def request_id_out do
    %Header{
      description: """
      Correlation id for this response. Mirrors the request's
      `X-Request-Id` when one was supplied; otherwise carries the
      id Phoenix generated for this request. Use for log and
      audit correlation.
      """,
      required: true,
      schema: %Schema{
        type: :string,
        minLength: 1,
        maxLength: 255,
        example: "GKd2jN1eZDCQUvIAACHD"
      }
    }
  end
end
