import Config

# Configure your database
config :bank, Bank.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "bank_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :bank, BankWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "uRSfKG8vUXwwCtGzCCQFSUODkCGTse1rKAvr9BakkiHHZMxpbhJHKHiT/CBBUgSu",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:bank, ~w(--sourcemap=inline --watch)]},
    esbuild_theme_init:
      {Esbuild, :install_and_run, [:theme_init, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:bank, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :bank, BankWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/bank_web/router\.ex$"E,
      ~r"lib/bank_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :bank, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :bank, Bank.Accounts.OAuthProvider, provider: Bank.Accounts.OAuthProvider.Stub

config :bank, Bank.Accounts.OAuthProvider.Stub, %{}

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Default connection to the TypeScript chain adapter for local dev.
# Production must set ADAPTER_BASE_URL / ADAPTER_DISPATCH_SECRET /
# ADAPTER_CALLBACK_SECRET in env; see config/runtime.exs.
config :bank, Bank.AdapterClient,
  base_url: "http://localhost:4100",
  dispatch_secret: "dev-adapter-dispatch-secret",
  callback_secret: "dev-adapter-callback-secret",
  req_options: []

# Telegram operator bot (epic #54): disabled by default in dev.
# Flip `enabled: true` and populate `operators` / `webhook_secret`
# locally to exercise the bot against a development chat and a tunnel
# (e.g. ngrok). Production wiring is env-driven in config/runtime.exs;
# see `Bank.Telegram.Config`.
config :bank, Bank.Telegram.Config,
  enabled: false,
  bot_token: nil,
  webhook_secret: nil,
  operators: []

# Base Sepolia public RPC endpoint for the redesigned wallet card's
# USDC balance reader. The Coinbase-operated `sepolia.base.org`
# requires no auth and is fine for local testing; production should
# override via env. Bank.Chains.KernelVerifier reads the same env in
# `config/runtime.exs` for the on-chain install verifier.
config :bank, Bank.Chains.BalanceReader,
  rpc_url: System.get_env("BASE_SEPOLIA_RPC_URL") || "https://sepolia.base.org/"

# 0x Swap API v2 provider used by `Bank.Decisions.SwapRouteResolver`
# for the swap-mode "Preview real 0x quote" path. The free tier
# (~1 req/sec) is plenty for demo / dev. Set `ZEROX_API_KEY` in the
# shell before running `mix phx.server`; without the key the provider
# returns `{:provider_error, %{reason: "missing_api_key"}}` and the
# preview UI surfaces a clean error rather than crashing.
config :bank, Bank.Stablecoins.Providers.ZeroX,
  base_url: "https://api.0x.org",
  api_key: System.get_env("ZEROX_API_KEY")

# On-chain install verifier — runs in `Bank.Runtime.Workers.VerifyInstallOnchain`
# after the browser-signed install confirms via the bundler. It reads
# `(smart_account_address, validation_id)` from the delegation row and
# performs `eth_getCode` + a 4337-account `getValidationConfig` call to
# pin that the chain state matches what the install attestation
# claimed. Without `:rpc_url` set, the worker returns
# `:rpc_not_configured` → marks the delegation `install_failed`
# (`onchain_verification_unreachable`) — that bit us until the browser
# install flow was wired end-to-end, because the worker fired against
# a config slot nobody had populated yet.
#
# Mirrors the `chain_rpc_url` alias chain for parity with the
# install-envelope path — same precedence, same fallback.
config :bank, Bank.Chains.KernelVerifier,
  rpc_url:
    System.get_env("BASE_SEPOLIA_RPC_URL") ||
      System.get_env("BASE_SEPOLIA_RPC") ||
      System.get_env("BASE_RPC_URL") ||
      "https://sepolia.base.org",
  # `:skip` until the Kernel-v3.1 `validationConfig(bytes21)` selector
  # is reconciled with the deployed kernel (see TODO in
  # `chain_adapter/scripts/verify-installed-validator.ts`). With
  # `:skip` the verifier still requires the smart account to be
  # deployed at the expected address; the per-permission install
  # check is deferred to the same integration ticket the adapter
  # script tracks. Production should set this to `:enforce` once
  # the selector is correct and add a contract test pinning the
  # decoded result shape.
  validation_id_check: :skip

# Browser-signed install bundler URL — required for the ZeroDev SDK
# in the browser to submit the install UserOperation against an
# ERC-4337 bundler. No public unauthenticated bundler exists for
# Base Sepolia, so set one of the env aliases below to a paid bundler
# (Pimlico / ZeroDev / Stackup / Alchemy / Coinbase CDP). The
# envelope endpoint falls back to a documented dummy URL when unset
# so the dev server still boots, but the ZeroDev SDK will fail loudly
# when it tries to hit `dev-no-bundler-configured` — that's the
# signal to set one of the env vars.
#
# Accepted env aliases (first non-empty wins):
#   1. BASE_SEPOLIA_BUNDLER_RPC — chain-specific, highest precedence.
#   2. BUNDLER_URL             — Phoenix-side historical alias.
#   3. BUNDLER_RPC_URL         — canonical alias used by the rest of
#      the codebase (chain_adapter/.env, smoke tests, mainnet
#      preflight). Sourcing `chain_adapter/.env` directly into
#      `mix phx.server` therefore works without an additional export.
config :bank, Bank.SessionPermissions.BrowserInstall,
  bundler_rpc_url:
    System.get_env("BASE_SEPOLIA_BUNDLER_RPC") ||
      System.get_env("BUNDLER_URL") ||
      System.get_env("BUNDLER_RPC_URL"),
  # Generic chain RPC (read-only). The browser-side ZeroDev SDK
  # builds a viem `publicClient` for `getSenderAddress` simulation
  # (`eth_call` against EntryPoint v0.7) before submitting the
  # install UserOp to the bundler. Pimlico's `/v2/<chain>/rpc`
  # endpoint serves bundler methods ONLY (`eth_sendUserOperation`,
  # `eth_estimateUserOperationGas`, etc.) and rejects generic chain
  # calls — passing it to `publicClient` makes `createKernelAccount`
  # crash with `Cannot read properties of undefined (reading 'match')`
  # because ZeroDev's revert-decoder regex fails on Pimlico's non-
  # EntryPoint reply shape. ZeroDev's hosted bundler (`rpc.zerodev.app`)
  # happens to serve both, which is why the install worked there until
  # the CSP fix landed. With Pimlico we MUST supply a separate chain
  # RPC URL — `BASE_RPC_URL` from `chain_adapter/.env` (defaults to
  # the public `https://sepolia.base.org` if missing).
  chain_rpc_url:
    System.get_env("BASE_SEPOLIA_RPC_URL") ||
      System.get_env("BASE_SEPOLIA_RPC") ||
      System.get_env("BASE_RPC_URL") ||
      "https://sepolia.base.org",
  # The EOA Phoenix embeds in the install envelope as the authorized
  # session signer. The ZeroDev SDK builds a `PermissionPlugin` whose
  # validator authorizes this EOA to act on behalf of the smart
  # account. The address MUST be derivable from the adapter's
  # `DELEGATION_SIGNER_KEY` — when both are set, the smoke task pins
  # consistency. Phoenix never holds the private key.
  session_signer_address: System.get_env("SESSION_SIGNER_ADDRESS"),
  # ── Kernel index split (#kernel-account-collision) ────────────────
  #
  # ZeroDev's `createKernelAccount` derives the smart-account
  # address CREATE2-style from `(sudo_validator_eoa, kernel_index)`.
  # The chain_adapter's runtime UserOps use `KERNEL_ACCOUNT_INDEX`
  # (default 0) with the operator EOA. If a BROWSER install also
  # used index 0 with the SAME EOA — which happens in dev when the
  # demo wallet imports `OPERATOR_PRIVATE_KEY` — the derived
  # address collides with the operator's already-deployed smart
  # account (`SMART_ACCOUNT_ADDRESS`) and the install UserOp
  # reverts with `AA23 reverted 0x756688fe` (Kernel's
  # `InvalidSignature()` because the existing account state
  # doesn't accept a fresh enable signature).
  #
  # The fix is to give the browser path its own index. Operator
  # stays on 0; browser defaults to 1. Phoenix-side preflight
  # refuses to issue an envelope when the connected user EOA
  # equals OPERATOR_ADDRESS AND the two indices collide — see
  # `Bank.SessionPermissions.BrowserInstall.check_kernel_index_collision/1`.
  #
  # NOTE: changing this index AFTER a delegation is installed will
  # derive a DIFFERENT smart account for the next install — the
  # old one is still on chain. Reuse the same index for the same
  # user EOA across reinstalls.
  operator_kernel_account_index:
    (System.get_env("KERNEL_ACCOUNT_INDEX") || "0") |> String.to_integer(),
  kernel_account_index:
    (System.get_env("BROWSER_KERNEL_ACCOUNT_INDEX") || "1") |> String.to_integer(),
  # The operator EOA the chain_adapter signs runtime UserOps with.
  # Phoenix uses this ONLY for the kernel-index-collision preflight;
  # the private key never leaves the adapter.
  operator_eoa_address: System.get_env("OPERATOR_ADDRESS")
