import Config

# Configure your database
config :bank, Bank.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "bank_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :bank, BankWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "uRSfKG8vUXwwCtGzCCQFSUODkCGTse1rKAvr9BakkiHHZMxpbhJHKHiT/CBBUgSu",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:bank, ~w(--sourcemap=inline --watch)]},
    esbuild_theme_init:
      {Esbuild, :install_and_run, [:theme_init, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:bank, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :bank, BankWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/bank_web/router\.ex$"E,
      ~r"lib/bank_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :bank, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :bank, Bank.Accounts.OAuthProvider, provider: Bank.Accounts.OAuthProvider.Stub

config :bank, Bank.Accounts.OAuthProvider.Stub, %{}

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Default connection to the TypeScript chain adapter for local dev.
# Production must set ADAPTER_BASE_URL / ADAPTER_DISPATCH_SECRET /
# ADAPTER_CALLBACK_SECRET in env; see config/runtime.exs.
config :bank, Bank.AdapterClient,
  base_url: "http://localhost:4100",
  dispatch_secret: "dev-adapter-dispatch-secret",
  callback_secret: "dev-adapter-callback-secret",
  req_options: []

# Telegram operator bot (epic #54): disabled by default in dev.
# Flip `enabled: true` and populate `operators` / `webhook_secret`
# locally to exercise the bot against a development chat and a tunnel
# (e.g. ngrok). Production wiring is env-driven in config/runtime.exs;
# see `Bank.Telegram.Config`.
config :bank, Bank.Telegram.Config,
  enabled: false,
  bot_token: nil,
  webhook_secret: nil,
  operators: []

# Base Sepolia public RPC endpoint for the redesigned wallet card's
# USDC balance reader. The Coinbase-operated `sepolia.base.org`
# requires no auth and is fine for local testing; production should
# override via env. Bank.Chains.KernelVerifier reads the same env in
# `config/runtime.exs` for the on-chain install verifier.
config :bank, Bank.Chains.BalanceReader,
  rpc_url: System.get_env("BASE_SEPOLIA_RPC_URL") || "https://sepolia.base.org/"

# Browser-signed install bundler URL — required for the ZeroDev SDK
# in the browser to submit the install UserOperation against an
# ERC-4337 bundler. No public unauthenticated bundler exists for
# Base Sepolia, so set BASE_SEPOLIA_BUNDLER_RPC in your local env to
# a paid bundler (Pimlico / ZeroDev / Stackup / Alchemy / Coinbase
# CDP). The envelope endpoint falls back to a documented dummy URL
# when unset so the dev server still boots, but the ZeroDev SDK will
# fail loudly when it tries to hit `dev-no-bundler-configured` —
# that's the signal to set the env var.
config :bank, Bank.SessionPermissions.BrowserInstall,
  bundler_rpc_url:
    System.get_env("BASE_SEPOLIA_BUNDLER_RPC") ||
      System.get_env("BUNDLER_URL")
