defmodule Bank.Repo.Migrations.CreateProviderHealthEvents do
  use Ecto.Migration

  @moduledoc """
  Creates the `provider_health_events` table for #422 — a durable,
  workspace-scoped log of stablecoin provider health transitions
  (the audit-side counterpart to the volatile ETS read store in
  `Bank.Stablecoins.ProviderHealth`).

  ## Why this exists

  ETS is the right hot-path read store for the
  `evaluate_for_intent/1` decision: per-node, low-latency,
  rebuilt from observed traffic. But ETS has no workspace
  dimension and resets on restart, so a `:degraded → :failing`
  flip cannot be tied back to an operator's workspace inbox
  (#234 acceptance: "operator notification when provider routing
  flips to failing"). The acceptance bullet for #422 is to add
  a durable per-workspace transition log that the runtime emits
  to whenever it observes a transition for an intent that
  carries a `workspace_id`. The ETS read-side is unchanged.

  ## Columns

    * `workspace_id` — `null: false`. FK with `on_delete: :restrict`,
      matching the `notifications` / business-data convention
      (workspace deletion is a manual operator action, never a
      cascade).
    * `provider` — `null: false`. Provider id string (e.g.
      `"zerox"`, `"oneinch"`); same shape `ProviderHealth.get/1`
      keys on.
    * `from_state` / `to_state` — `null: false`. Text
      discriminators; the schema layer constrains values to
      `:unknown | :healthy | :degraded | :failing`.
    * `route_session_id` — `null: false`. UUID generated by
      `evaluate_for_intent/1` for one routing attempt; lets the
      notification dedupe key collapse retries within the same
      session into a single inbox row while still emitting a
      fresh row on the next routing attempt.
    * `evidence` — `null: false`, default `'{}'::jsonb`. Map of
      controlled fields only (success_count, failure_count) —
      provider-supplied free-text reasons are NEVER persisted
      here so a future read-side surface cannot leak secret
      shapes.
    * `observed_at` — `null: false`. Wall-clock for the
      transition; separate from `inserted_at` so a future
      replay/import pipeline can backfill historical rows.
    * `inserted_at` / `updated_at` — standard.

  ## Indexes

    * Workspace-scoped time-ordered listing for the operator
      health page (forthcoming).
    * Workspace + provider + session triple to look up "did we
      already record this transition for this routing attempt?"
      — the durable belt for the `notifications` dedupe key.

  ## Insert-only semantics

  Like `audit_events`, this table is append-only at the context
  layer. The migration does not enforce immutability with
  triggers — the read-side has no schema for updates, so any
  caller that wanted to UPDATE would have to write raw SQL and
  bypass the public surface.
  """

  def change do
    create table(:provider_health_events, primary_key: false) do
      add :id, :binary_id, primary_key: true

      add :workspace_id,
          references(:workspaces, type: :binary_id, on_delete: :restrict),
          null: false

      add :provider, :string, null: false, size: 64
      add :from_state, :string, null: false, size: 16
      add :to_state, :string, null: false, size: 16

      add :route_session_id, :binary_id, null: false

      add :evidence, :map, null: false, default: %{}

      add :observed_at, :utc_datetime_usec, null: false

      timestamps(type: :utc_datetime_usec)
    end

    create index(:provider_health_events, [:workspace_id, :observed_at],
             name: :provider_health_events_workspace_observed_at_idx
           )

    create index(
             :provider_health_events,
             [:workspace_id, :provider, :route_session_id, :to_state],
             name: :provider_health_events_workspace_session_state_idx
           )
  end
end
